
src-data-names:
	mkdir src-data-names
	ln -s ../src-data/Charlottenburg-Wilmersdorf/ src-data-names/cburg_wilmersdf
	ln -s ../src-data/Friedrichshain-Kreuzberg/ src-data-names/fhain_xberg
	ln -s ../src-data/Lichtenberg/ src-data-names/lichtenbg
	ln -s ../src-data/Marzahn-Hellersdorf/ src-data-names/marzahn_hellersdf
	ln -s ../src-data/Mitte/ src-data-names/mitte
	ln -s ../src-data/Neukoelln/ src-data-names/neukoelln
	ln -s ../src-data/Pankow/ src-data-names/pankow
	ln -s ../src-data/Reinickendorf/ src-data-names/reinickendf
	ln -s ../src-data/Spandau/ src-data-names/spandau
	ln -s ../src-data/Steglitz-Zehlendorf/ src-data-names/steglitz_zehlendf
	ln -s ../src-data/Tempelhof-Schoeneberg/ src-data-names/tempelhf_schoenebg
	ln -s ../src-data/Treptow-Koepenick/ src-data-names/treptow_koepenick
