
src-names:
	mkdir src-names
	ln -s ../src-citygml/Charlottenburg-Wilmersdorf/ src-names/cburg_wilmersdf
	ln -s ../src-citygml/Friedrichshain-Kreuzberg/ src-names/fhain_xberg
	ln -s ../src-citygml/Lichtenberg/ src-names/lichtenbg
	ln -s ../src-citygml/Marzahn-Hellersdorf/ src-names/marzahn_hellersdf
	ln -s ../src-citygml/Mitte/ src-names/mitte
	ln -s ../src-citygml/Neukoelln/ src-names/neukoelln
	ln -s ../src-citygml/Pankow/ src-names/pankow
	ln -s ../src-citygml/Reinickendorf/ src-names/reinickendf
	ln -s ../src-citygml/Spandau/ src-names/spandau
	ln -s ../src-citygml/Steglitz-Zehlendorf/ src-names/steglitz_zehlendf
	ln -s ../src-citygml/Tempelhof-Schoeneberg/ src-names/tempelhf_schoenebg
	ln -s ../src-citygml/Treptow-Koepenick/ src-names/treptow_koepenick
