#!/bin/sh
mkdir -p cpp-sections
(
echo "# autogenerated from $0"
echo
echo "objs: cpps \\"
cd gml-sections
for section in *; do
  echo " s_${section}.o \\"
done
echo
echo

echo "%.o: %.cpp"
echo "\tg++ -I../include -c \$<"
echo
echo

echo "cpps: \\"

cd gml-sections
for section in *; do
  echo " s_${section}.cpp \\"
done
echo
echo

for section in *; do
  echo "s_${section}.cpp: ../gml-sections/${section}"
  echo "\t../parse_gml_section.py ../gml-sections/${section}"
  echo
done


) > cpp-sections/Makefile

